trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
      checkLatest: true
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run package
    displayName: 'npm install and build'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'publish --access public'
      customEndpoint: 'NPM - 4lch4'
    displayName: 'Publish Module'
